sources:
  - Jaro.glyphs
axisOrder:
  - opsz
  - wght
familyName: Jaro
stat:
  Jaro[opsz].ttf:
  - name: Optical size
    tag: opsz
    values:
    - name: 6pt
      value: 6
    - name: 12pt
      value: 12
    - name: 24pt
      value: 24
    - name: 48pt
      value: 48
    - name: 72pt
      value: 72
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      